version: "2"
services:
  app:
    container_name: birds-supply-server
    restart: always
    image: birds-supply-server
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
